[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "vdom/_version.py"
tag_prefix = ""
parentdir_prefix = "vdom-"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''
skip-string-normalization = true
